#!/bin/bash

# Daily ClamAV system scan (daily-clamdscan) v1.01

# OVERVIEW: There exists three (3) available basic return codes for ClamAV. Return code 0 = success, return code 1 = infection(s), and return code 2 = errors.
# Depending on the execution of ClamAV and the order in which it encounters any infections and/or errors the final return code will always prevail. Therefore,
# if you have both infected files (return code 1) and errors (return code 2) this can result in either return code 1 or 2 depending the order in which ClamAV encounters them.
# This all but negates any proper return code interpretation and complicates any scripting with odd logic.

# PURPOSE: This script aims to simply determine if a non-zero (1 and/or 2) return code is present after execution and notify (email) an administrator for further action, otherwise silently terminate.
# All of the needed variable definitions can be updated occordingly as applicable. The alert email notification includes the ClamAV version, scan target(s), scan size, and a log attachment.
# You can additionally control the log rotation interval.

# Script variable definitions
clamav_ver=$( clamd --version );
scan_dir="/";

# Determine the scan size
for s in ${scan_dir}; do
  dirsize=$(du -sh "$s" 2>/dev/null | cut -f1);
done

email_subject="ClamAV: Infections and/or Errors Encountered";
email_message="Version: "$clamav_ver"\nStarting a recursive scan of the "$s" directory. The size of the directory is: "$dirsize".\n\nInfections and/or errors have been encountered during the scan. Please review the log attached below for further details:\n";
monitoring_email="monitoring@zer0systems.com";
logfile="/var/log/clamav/clamdscan-$(date +'%Y-%m-%d').log";
log_rotate="+30";

# Execute the scan and quarantine any infections
/usr/bin/clamdscan --multiscan --fdpass --move=/root/.quarantine --log="$logfile" "$scan_dir";

# Capture the scan return code
retcode="$?";

# Log rotation (days)
find /var/log/clamav -type f -mtime "$log_rotate" -delete;

# Evaluate the return code status, alert or terminate
if [ "$retcode" -ne "0" ]; then
  echo -e "$email_message" | s-nail -s "$email_subject" -a "$logfile" "$monitoring_email";
  exit "$retcode"
else
  exit 0
fi
